# Generated by Django 4.2.9 on 2024-01-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=0),
        ),
    ]
