# Generated by Django 4.2.9 on 2024-01-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0002_remove_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
