# Generated by Django 4.2.9 on 2024-01-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0005_userprofile_birth_date_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='kinky_user',
        ),
    ]
