# Generated by Django 5.0.1 on 2024-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0006_rename_user_userprofile_kinky_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='kinky_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
