# Generated by Django 5.0.1 on 2024-01-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0008_userprofile_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
