# Generated by Django 5.0.1 on 2024-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0013_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
