# Generated by Django 5.0.1 on 2024-01-29 12:43

import kinky.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0016_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=kinky.models.user_image_upload_path),
        ),
    ]
