# Generated by Django 5.0.1 on 2024-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0017_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='images_path',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
