# Generated by Django 5.0.1 on 2024-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0018_userprofile_images_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_counter',
            field=models.IntegerField(default=0),
        ),
    ]
