# Generated by Django 5.0.1 on 2024-01-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0020_userprofile_user_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_images',
        ),
    ]
