# Generated by Django 5.0.1 on 2024-01-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0022_imagesfromuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_counter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='images_path',
        ),
    ]
