# Generated by Django 5.0.1 on 2024-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0023_remove_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_counter',
            field=models.IntegerField(default=0),
        ),
    ]
