# Generated by Django 5.0.1 on 2024-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0025_remove_imagesfromuser_image_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
