# Generated by Django 5.0.1 on 2024-01-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0028_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
