# Generated by Django 5.0.1 on 2024-01-31 09:56

import kinky.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0029_remove_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=kinky.models.user_image_upload_path),
        ),
    ]
