# Generated by Django 5.0.1 on 2024-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinky', '0033_imagesfromuser_date_imagesfromuser_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feed_page',
            field=models.IntegerField(default=0),
        ),
    ]
